apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.Namespacename }}
  name: {{ .Values.Servicename }}
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  type: NodePort
  selector:
    {{- toYaml .Values.selector| nindent 4 }}